#include <ledmtx_core.h>
#include <ledmtx_fontstd.h>
#include <signal.h>
#include <stdio.h>

// ledmtx_modegen_modes.h is auto-generated by `ledmtx_modegen`; see Makefile.
#include "ledmtx_modegen_modes.h"

__CONFIG(__CONFIG1H, _HS_OSC_1H);
__CONFIG(__CONFIG2H, _WDT_OFF_2H);
__CONFIG(__CONFIG4L, _LVP_OFF_4L);

// These macros are required even if not using any additional modules
LEDMTX_BEGIN_MODULES_INIT
LEDMTX_END_MODULES_INIT

// Reserve enough memory for a 32x7 framebuffer
LEDMTX_DECLARE_FRAMEBUFFER(32, 7)

DEF_INTLOW(low_int)
DEF_HANDLER(SIG_TMR0, _tmr0_handler)
END_DEF

// The ISR for Timer 0.  In this simple example, it just calls the
// driver-specific vertical refresh routine
SIGHANDLERNAKED(_tmr0_handler) {
  LEDMTX_BEGIN_ISR
  LEDMTX_VERTREFRESH
  LEDMTX_END_ISR
}

void main(void) {
  TRISA = 0xe0;
  ADCON1 = 0x0f;

  ledmtx_init(LEDMTX_INIT_CLEAR | LEDMTX_INIT_TMR0, LEDMTX__DEFAULT_WIDTH,
              LEDMTX__DEFAULT_HEIGHT, LEDMTX__DEFAULT_TMR0H,
              LEDMTX__DEFAULT_TMR0L, LEDMTX__DEFAULT_T0CON);
  ledmtx_setfont(ledmtx_font5x7);
  stdout = STREAM_USER;

  printf("hello\n");
}
