# Target device
P18FXXX = 18f452

ifdef INSTALL_PREFIX
LIBDIR = $(INSTALL_PREFIX)/lib/
INCLUDEDIR = $(INSTALL_PREFIX)/include/
BINDIR = $(INSTALL_PREFIX)/bin/
else
INCLUDEDIR ?= $(SRCDIR)/../include
endif

GPLIB = gplib
AS = gpasm
ASFLAGS = -I$(SRCDIR) -I$(INCLUDEDIR) -p $(P18FXXX) -w 0

# Optional features
ifdef ENABLE_DOUBLE_BUFFER
ENABLE_DOUBLE_BUFFER = 1
endif
ENABLE_DOUBLE_BUFFER ?= 0

ifdef ENABLE_VIEWPORT
ENABLE_VIEWPORT = 1
endif
ENABLE_VIEWPORT ?= 0
